Hopefully simplified the build system a lot

diff --git a/DeforaOS/Apps/Devel/src/scripts/targets/Linux-i386 b/DeforaOS/Apps/Devel/src/scripts/targets/Linux-i386
--- a/DeforaOS/Apps/Devel/src/scripts/targets/Linux-i386
+++ b/DeforaOS/Apps/Devel/src/scripts/targets/Linux-i386
@@ -3,8 +3,7 @@
 
 
 #variables
-[ -z "$MKFS" ] && MKFS="mke2fs -F"
-[ -z "$TUNE2FS" ] && TUNE2FS="tune2fs"
+#XXX insert i386-specific variables here (grub...)
 
 
 #includes
@@ -12,13 +11,24 @@ source "`dirname $0`/Apps/Devel/src/scripts/targets/Linux"
 
 
 #functions
-target_image()
+#private
+_image_image()
 {
+	USAGE="Options for $IMAGE_TYPE on $TARGET:\n\
+  IMAGE_FILE	Where to write the filesystem image\n\
+  IMAGE_KERNEL	Path to the kernel\n\
+  IMAGE_SIZE	Size of the filesystem image in kilobytes\n\
+  MKFS		Command used to create the filesystem"
+
+	#sanity check
+	check "$USAGE" DD DESTDIR DEVZERO IMAGE_FILE IMAGE_KERNEL IMAGE_SIZE \
+		MKDIR MKFS MOUNT UMOUNT
+
+	$MKDIR "$DESTDIR"					|| exit 2
 	$UMOUNT "$DESTDIR"
-	$MKDIR "$DESTDIR"			|| exit 2
-	$DD if="$DEVZERO" of="$DISK_IMAGE" count="$DISK_SIZE" &&
-	$MKFS "$DISK_IMAGE"			|| exit 2
-	$MOUNT "$DISK_IMAGE" "$DESTDIR"		|| exit 2
+	$DD if="$DEVZERO" of="$IMAGE_FILE" count="$IMAGE_SIZE" &&
+	$MKFS "$IMAGE_FILE"					|| exit 2
+	$MOUNT "$IMAGE_FILE" "$DESTDIR"				|| exit 2
 	target "install"
 	RET=$?
 	$UMOUNT "$DESTDIR"
@@ -26,54 +36,93 @@ target_image()
 }
 
 
-target_iso()
+_image_iso()
 {
+	USAGE="Options for $IMAGE_TYPE on $TARGET:\n\
+  IMAGE_FILE	Where to write the filesystem image\n\
+  IMAGE_KERNEL	Path to the kernel\n\
+  IMAGE_MODULES	Path to a tar.gz archive of kernel modules (optional)\n\
+  IMAGE_RAMDISK	Path to the ramdisk (optional)\n\
+  IMAGE_SIZE	Size of the filesystem image in kilobytes\n\
+  KERNEL_ARGS	Additional arguments to give to the kernel (optional)\n\
+  MKISOFS	Command used to create the ISO image"
+
+	#sanity check
+	check "$USAGE" DESTDIR KERNEL IMAGE_FILE IMAGE_KERNEL IMAGE_SIZE \
+		INSTALL MKDIR MKISOFS MOUNT RAMDISK TAR UMOUNT
+
 	$MKDIR "$DESTDIR/boot/grub"				|| exit 2
-	$CP "/usr/lib/grub/i386-pc/stage2_eltorito" \
+	$INSTALL -m 644 "/usr/lib/grub/i386-pc/stage2_eltorito" \
 	"$DESTDIR/boot/grub"					|| exit 2
-	$CP "$KERNEL" "$DESTDIR/boot/uKernel"			|| exit 2
-	if [ ! -z "$RAMDISK_IMAGE" ]; then
-		$CP "$RAMDISK_IMAGE" "$DESTDIR/boot/initrd.img"
-		GRUB_INITRD="initrd /boot/initrd.img"
+	$INSTALL -m 755 "$IMAGE_KERNEL" "$DESTDIR/$KERNEL"	|| exit 2
+	if [ ! -z "$IMAGE_RAMDISK" ]; then
+		$INSTALL -m 644 "$IMAGE_RAMDISK" "$DESTDIR/$RAMDISK"
+		GRUB_INITRD="initrd $RAMDISK"
 	fi
 	$CAT > "$DESTDIR/boot/grub/menu.lst" << EOF
 default 0
 timeout 10
 
 title $VENDOR
-kernel /boot/uKernel $KERNEL_ARGS
+kernel $KERNEL $KERNEL_ARGS
 $GRUB_INITRD
 EOF
-	[ ! -z "$KERNEL_MODULES" ] && cat "$KERNEL_MODULES" | \
-			(cd "$DESTDIR" && tar xzf -)
+	[ ! -z "$IMAGE_MODULES" ] && cat "$IMAGE_MODULES" | \
+			(cd "$DESTDIR" && $TAR -xzf -)
 	$MKISOFS -b "boot/grub/stage2_eltorito" -no-emul-boot \
 			-boot-load-size 4 -boot-info-table \
-			-o "$CDROM_IMAGE" "$DESTDIR"
+			-o "$IMAGE_FILE" "$DESTDIR"
 }
 
 
-target_ramdisk()
+_image_ramdisk()
 {
-	[ -z "$MOUNTPOINT" ] && error "MOUNTPOINT needs to be set"
-	$UMOUNT "$MOUNTPOINT"
+	USAGE="Options for $IMAGE_TYPE on $TARGET:\n\
+  IMAGE_FILE	Where to write the filesystem image\n\
+  IMAGE_SIZE	Size of the filesystem image in kilobytes\n\
+  MKFS		Command used to format the ramdisk image\n\
+  MOUNTPOINT	Path where to temporarily mount the ramdisk image"
+
+	#sanity check
+	check "$USAGE" DD DEVZERO DU GZIP IMAGE_FILE IMAGE_SIZE INSTALL LN \
+	MKDIR MKFS MOUNTPOINT MV UMOUNT
+
 	$MKDIR "$MOUNTPOINT"
-	$DD if="$DEVZERO" of="$RAMDISK_IMAGE" count="$RAMDISK_SIZE"|| exit 2
-	$MKFS "$RAMDISK_IMAGE"					|| exit 2
-	[ ! -z "$TUNE2FS" ] && $TUNE2FS -i 0 "$RAMDISK_IMAGE"
-	$MOUNT "$RAMDISK_IMAGE" "$MOUNTPOINT"			|| exit 2
+	$UMOUNT "$MOUNTPOINT"
+	$DD if="$DEVZERO" of="$IMAGE_FILE" count="$IMAGE_SIZE"	|| exit 2
+	$MKFS "$IMAGE_FILE"					|| exit 2
+	[ ! -z "$TUNE2FS" ] && $TUNE2FS -i 0 "$IMAGE_FILE"
+	#FIXME umount on subsequent failures
+	$MOUNT "$IMAGE_FILE" "$MOUNTPOINT"			|| exit 2
+
+	#compile and install linuxrc
 	SUBDIRS="Apps/Unix/src/others/tools" target linuxrc	|| exit 2
 
-	DESTDIR="$MOUNTPOINT" _create_directories 'dev' 'proc' 'mnt/cdrom' \
-		'sbin'
-
+	DESTDIR="$MOUNTPOINT" _create_directories "dev" "proc" "mnt/cdrom" \
+		"sbin"
 	$LN "../mnt/cdrom/usr/bin/sh" "$MOUNTPOINT/sbin/init"
-	$CP "Apps/Unix/src/others/tools/linuxrc" "$MOUNTPOINT"	|| exit 2
+	$INSTALL -m 755 "Apps/Unix/src/others/tools/linuxrc" \
+	"$MOUNTPOINT/linuxrc"					|| exit 2
 	$UMOUNT "$MOUNTPOINT"
 
 	echo
 	echo -n "Compressing ramdisk:"
-	$GZIP "$RAMDISK_IMAGE"					|| exit 2
-	$MV "$RAMDISK_IMAGE.gz" "$RAMDISK_IMAGE"		|| exit 2
+	$GZIP "$IMAGE_FILE"					|| exit 2
+	$MV "$IMAGE_FILE.gz" "$IMAGE_FILE"			|| exit 2
 	echo
-	$DU "$RAMDISK_IMAGE"
+	$DU "$IMAGE_FILE"
+}
+
+
+#public
+target_image()
+{
+	case "$IMAGE_TYPE" in
+		"iso")
+			return _image_iso
+		"ramdisk")
+			return _image_ramdisk
+		*)
+			return _image_image
+	esac
 }
