Using getext2fs instead of a loop mount

diff --git a/DeforaOS/Apps/Devel/src/scripts/targets/Linux b/DeforaOS/Apps/Devel/src/scripts/targets/Linux
--- a/DeforaOS/Apps/Devel/src/scripts/targets/Linux
+++ b/DeforaOS/Apps/Devel/src/scripts/targets/Linux
@@ -3,6 +3,7 @@
 
 
 
+#variables
 [ -z "$DU" ]	&& DU="du -h"
 [ -z "$GZIP" ]	&& GZIP="gzip -9"
 [ -z "$KERNEL" ]&& KERNEL="/boot/vmlinuz"
@@ -14,3 +15,20 @@
 [ -z "$TAR" ]	&& TAR="tar"
 [ -z "$TUNE2FS" ]&& TUNE2FS="tune2fs"
 [ -z "$UMOUNT" ]&& UMOUNT="$SUDO umount"
+
+
+
+#functions
+#private
+#create_directories
+_create_directories()
+{
+	echo
+	echo -n "Creating missing directories:"
+	while true; do
+		echo -n " $1"
+		$MKDIR "$DESTDIR/$1"				|| exit 2
+		shift || break
+	done
+	echo
+}
